##
## Create a release archive for Linux.
##
name: Linux Release
on: [push]
jobs:
  create-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - uses: actions-rs/toolchain@v1
        name: Install minimal Rust build system
        with:
          toolchain: 1.44.1
          default: true

      - run: make release
        name: Build software

      - name: Create release archives
        run: |
           rm -rf /tmp/inst
           make DESTDIR=/tmp/inst install
           cd /tmp/inst
           tar zcf /tmp/mdcat.tar.gz .
           zip -r /tmp/mdcat.zip .
